# Введение в методы анализа данных. Язык Python.

## Лекция 7. Введение в машинное обучение. Нейросети.
<br><br><br><br>
__Аксентьев Артем (akseart@ya.ru)__

__Ксемидов Борис (bworkboris@yandex.ru)__
<br>

## Нейрон

<center>
<img src="data/neuron.png" width="600" height="400">
</center>

<center>
<img src="data/neuron.jpg" width="600" height="400">
</center>

Примеры активационных функций:
- ReLU;
- Sigmoid;
- TanH.

**RELU**

<center>
<img src="data/relu.png" width="600" height="400">
</center>

In [6]:
import numpy as np

def relu(x):
    x = x.copy()
    x[x <= 0] = 0
    return x


class ReLUNeuron:
    def __init__(self, inputs) -> None:
        self.weights = np.random.random((1, inputs))

    def forward(self, x):
        return relu(self.weights @ x)


n = ReLUNeuron(2)
print(n.weights)
n.forward(np.array([1, 1]))

[[0.16680922 0.83821756]]


array([1.00502678])

**Sigmoid**

<center>
<img src="data/sigmoid.png" width="600" height="400">
</center>

In [8]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))


class SigmoidNeuron:
    def __init__(self, inputs) -> None:
        self.weights = np.random.random((1, inputs))

    def forward(self, x):
        return sigmoid(self.weights @ x)


n = SigmoidNeuron(2)
print(n.weights)
n.forward(np.array([1, 1]))

[[0.3170711  0.86598411]]


array([0.76549669])

In [9]:
import numpy as np

def linear(x):
    return x


class LinNeuron:
    def __init__(self, inputs) -> None:
        self.weights = np.random.random((1, inputs))

    def forward(self, x):
        return linear(self.weights @ x)


n = LinNeuron(2)
print(n.weights)
n.forward(np.array([1, 1]))

[[0.72576796 0.63560252]]


array([1.36137048])

## Нейросеть

<center>
<img src="data/image001.png" width="600" height="400">
</center>

<center>
<img src="data/net.png" width="600" height="400">
</center>

In [12]:
import torch
import torch.nn as nn
 
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(60, 180)
        self.relu = nn.ReLU()
        self.output = nn.Linear(180, 1)
        self.sigmoid = nn.Sigmoid()
 
    def forward(self, x):
        x = self.relu(self.hidden(x))
        x = self.sigmoid(self.output(x))
        return x

In [13]:
net = Net()
net(torch.randn(60))

tensor([0.4654], grad_fn=<SigmoidBackward0>)

## Полезные ссылки
- [Softmax](https://machinelearningmastery.com/softmax-activation-function-with-python/)
- [Сверточные нейронные сети](https://neurohive.io/ru/osnovy-data-science/glubokaya-svertochnaja-nejronnaja-set/)
- Рекуррентные нейронные сети